-- Inserir Categorias de RECEITA
INSERT INTO categoria (categoria) VALUES
('Vendas'),
('Serviços Prestados'),
('Aluguel de Imóveis'),
('Dividendos'),
('Investimentos'),
('Comissões'),
('Consultoria'),
('Frete'),
('Venda de Produtos'),
('Rendimentos de Aplicações'),
('Lucro de Parcerias'),
('Licenciamento'),
('Royalties'),
('Promoções e Vendas Especiais'),
('Doações'),
('Salários'),
('Fornecedores'),
('Aluguel'),
('Contas de Energia'),
('Água e Saneamento'),
('Materiais de Escritório'),
('Publicidade e Marketing'),
('Transportes'),
('Impostos'),
('Serviços de Contabilidade'),
('Despesas Administrativas'),
('Seguros'),
('Empréstimos e Financiamentos'),
('Despesas com TI'),
('Manutenção de Equipamentos');
